### ISSUE TITLE
[wpe-2.38] Canvas rendering problems with webkit resolution set to 1080p

### ISSUE THREAD

**Issue by jakub-gocol-red** [Metrological/WebKitForWayland#1105]
Environment:
* wpe2.38 with WPEBackend-rdk
* enabled accelerated 2d canvas
* WPE_INIT_VIEW_WIDTH and WPE_INIT_VIEW_HEIGHT environment variables set to 1920 x 1080

Reproduction step:
1. Open [euronews application](https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#app:com.metrological.app.Euronews)
2. Check if page rendered correctly; If yes, go back to previous page and open euronews again. It's not 100% reproduction, but it usually reproduces in under 5 reloads.

Notes:
* Issue doesn't reproduce when webkit resolution is set to 1280x720, when accelerated 2d canvas is disabled or on wpe-2.22
* Issue only reproduces on applications that use lightning framework
* It's usually visible on fonts (but not always)

here are few examples of broken rendering side by side with correct rendering
![image](https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/93707234/43c231a7-76a6-4614-b511-b8eb796c91a1)
![image](https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/93707234/114db968-2aff-4c1d-8d34-470b327e153a)
![image](https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/93707234/5920753e-f7fa-4a48-b301-429902989a78)
![image](https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/93707234/2a01cd55-ebf5-4b8d-90bf-0138b6858b58)
![image](https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/93707234/8061eca0-a8de-4272-91f8-7c16488de095)

**Comment by magomez** [comment]
As you mention, the problem comes from joining lightning with accelerated canvas and the 1080 resolution:
- Lightning uses canvases to render text, and the uploads the content into textures to show it.
- When accelerated canvas is enabled, all the canvases are accelerated, except those that are smaller than 256x256.
- Accelerated canvases are rendered with cairo-gl, which is the one adding the glitches when rendering text (we looked into it but we haven't found the problem yet).

So, when using 720p, the canvases used by lightning to render text are smaller than 256x256, to they are not accelerated and the issue doesn't happen. When using 1080p though, the size of the canvases used is bigger than 256x256, so they become accelerated and the glitches happen.

I've pushed bc983a91ee80758f297efc39e83b0a694e4bf050 to the wpe-2.38 branch with a workaround for this. It basically disables accelerated canvases for sizes smaller than 1/4 of the display size. This should be enough to fix the issue in most cases. But if it's not, we can always increase it a bit more. The important case where we need the canvas accelerated is the fullscreen case, and that's covered anyway.

@jakub-gocol-red could you verify that the fix works for you, and close this if everything is ok?

**Comment by jakub-gocol-red** [comment]
> could you verify that the fix works for you, and close this if everything is ok?
This patch solved all issues I mentioned in original comment.
