### ISSUE TITLE
[wpe-2.38] Edit-list support

### ISSUE THREAD

**Issue by varumugam123** [Metrological/WebKitForWayland#1185]
This request is to port fdf2f014629a4b4e93f43cec0be4698aa640b826 and any dependent changes to support edit-list.

**Comment by eocanha** [comment]
Are you asking to port the edit lists support commit to 2.38? It's already present there, in this commit: https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/bf69bf7f9edc397b39b76d90a861362b8182088a

**Comment by varumugam123** [comment]
Hi @eocanha , Sorry I am not following. Do you mean, wpe-2.38 already has the edit list support? I checked the latest wpe-2.38 tip, I don't see the changes there.

**Comment by eocanha** [comment]
Ah, now I see. It's more complex than that. What happened is that the https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/fdf2f014629a4b4e93f43cec0be4698aa640b826 commit you refer to is actually present (as https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/bf69bf7f9edc397b39b76d90a861362b8182088a) in the wpe-2.38 commit history. However, subsequent commit https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/6f5e4c1be001e30771d101bcddedc11ae62cce45 reverted that change. And that's still the current state upstream, as you can see: https://github.com/WebKit/WebKit/blob/main/Source/WebCore/platform/graphics/gstreamer/mse/AppendPipeline.cpp#L408

Maybe @ntrrgc (in charge of pushing forward this kind of new stuff upstream, and author of the Edit Lists patch) can give some information about the status of that upstream line of work, or what other commits/features it's still pending on.

What I wouldn't do would be to just reintroduce the commit if it was reverted upstream because it created regressions. At least not before some previous discussion of the pros and cons.

**Comment by ntrrgc** [comment]
This is what Philippe commented about the reasons to revert the patch: https://bugs.webkit.org/show_bug.cgi?id=231019#c19

At this point, the patch is still reverted upstream. Unfortunately I've been buried by more serious issues all this time (and still am), so I haven't been able to give the edit list issue attention since. I haven't forgotten it, and it's in my stack, but I cannot justify to prioritize it over, for instance, races that crash the player on early flushes, so it likely will still be a relatively long time until I can give the edit lists issues the focus they need. For now I'm ignoring the issues with inaccurate timestamps they cause as long as playback works.

**Comment by modeveci** [comment]
@eocanha @philn Can we look at this issue in the scope of downstream 2.38? It is a needed feature for deployment of 2.38 on platforms and has priority. thank you very much!
Ozgur

**Comment by eocanha** [comment]
I'm putting this task as the next one in my queue of priorities.

**Comment by eocanha** [comment]
Commit reintroduced on downstream wpe-2.38 as https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/c6df424cddcd1aa0976bc705133358ae0b0af61c
