### ISSUE TITLE
TG4 - Playback is stuck after performing extensive forward and rewind action

### ISSUE THREAD

**Issue by janani-balasubramanian-infosys** [Metrological/WebKitForWayland#1401]
In Sagemcom Accelerator device, in TG4 app, while trying to forward and rewind continuously in any content, after sometime, the playback is stuck and a blank screen appears. From the logs, it can be observed that after the playback is stuck, the seeking is also stuck at a particular value and does not perform further seek operations. 

To reproduce the issue:
1.Open TG4 Application (https://smarttv.tg4.ie)
2. Try to play any content 
3.Try to perform fast forward/fast backward actions continuously and multiple times or extensively

Frequency (percentage):
20%

Note: 
This issue is not seen in wpe 2.22.

Attached log file and video for reference

https://github.com/user-attachments/assets/3aacfe75-3dbd-473b-81f9-2579b725cf66
[sgm.txt](https://github.com/user-attachments/files/17026156/sgm.txt)

**Comment by calvaris** [comment]
From what I see, what is going on here the problem seems to be in the web app. What I see that is going on:

1. seek begins
2. we don't have the playback range, set ready state to have metadata
3. web app begins to append the range
...
5. we do another seek
6. we don't have the playback range, ready state was already have metadata
7. web app keeps appending a range that does not correspond with the last initiated seek
8. seek can never complete

IMHO, the browser is working as expected so I am closing this.

**Comment by janani-balasubramanian-infosys** [comment]
@calvaris  TG4 app uses MSE based playback. This issue is only seen in TG4 app in wpe 2.38 and not in other MSE based apps such as NPO and videoland. 

In wpe 2.22 version, the issue is not seen.

**Comment by janani-balasubramanian-infosys** [comment]
Attaching the wpe 2.22 logs here
[logs.txt](https://github.com/user-attachments/files/17343229/logs.txt)

**Comment by janani-balasubramanian-infosys** [comment]
@calvaris  Since the issue is seen in wpe 2.22 too, Please let me know if we can continue the discussion in the same ticket or I can create a new ticket.

**Comment by calvaris** [comment]
Hi, my intention is neither continuing the discussion, nor opening a new ticket for 2.22. I closed this issue because my investigation demonstrated that this IS a problem with the web app, not with the browser.
