### ISSUE TITLE
Issue with WPEDatabaseProcess

### ISSUE THREAD

**Issue by ktxxt** [Metrological/WebKitForWayland#197]
Hello :)

I can not find anywhere the docs to answer my question, "How is the WPEDatabaseProcess created?", except you use indexDB, which I don't. However, when I launch wpe, the process gets created every time.

**Comment by zdobersek** [comment]
Other than through Web content, the DatabaseProcess can also be spawned when using APIs like WKWebsiteDataStoreRemoveAllIndexedDatabases().

If that's not the case -- is this occurring when loading some specific Web page?

**Comment by ktxxt** [comment]
I am not using any API. I open a index.html localy, which opens another web page in an `iframe`.
Is there any way my JavaScript activates it? If so, which JavaScript functions cause it to spawn?

I'm posting this issue, because, when I disable the internet connection, the DatabaseProcess fails and my app goes black screen, so I'm looking towards a way not to spawn the process at all.

**Comment by zdobersek** [comment]
In that case it probably spawns because of the content that's loaded via iframe, specifically by using the IndexedDB API.

about:blank shouldn't spawn the database process, of course. Try loading different pages in iframe to see whether it's indeed the content there -- e.g. google.com doesn't appear to be spawning it either.

**Comment by ktxxt** [comment]
Thank you for the info. Closing this one.
