### ISSUE TITLE
question on buildroot: difference between configs

### ISSUE THREAD

**Issue by SamDecrock** [Metrological/WebKitForWayland#557]
Hi,

I'm trying to compile WPEWebKit using the buildroot repo you provided. I was wondering what the main difference is between

`raspberrypi3+_wpe_ibc_defconfig`
and 
`raspberrypi3_wpe_defconfig`

Thanks

**Comment by hlev** [comment]
Had a quick look at the diff between the two:
- from the naming, it seems the former is intended for the newer RPI3 B+ board, the latter is for the standard RPI3 B although I think either should work on either device, both include the device trees for RPI3B, RPI3B+ and RPI CM3 boards 
- `ibc` uses a 4.14 kernel, the other is 4.9
- `ibc` builds in-kernel-tree device tree overlays, but I don't know if it actually uses those or the pre-compiled ones that it gets from `rpi-firmware` because both defconfigs include that package
- `ibc` configures a login TTY on ttyAMA0
- `ibc` includes the ALSA GStreamer plugin
- the standard one includes firmware for the RALINK_RT2XX wifi stick and the proprietary  broadcom_bcm43xx (on-board) firmware.
- they configure WPEFramework a bit differently, it seems `ibc` is not interested in WiFi at all, it only includes the NETWORKCONTROL plugin, the standard one includes both WIFICONTROL and NETWORKCONTROL and DHCPSERVER
- the standard defconfig includes a few more `wpa_supplicant` capabilites than the default, the `ibc` one may not have `wpa_supplicant` at all
- `ibc` has these flags as well for WPEFramework/WPEWebkit that I am not fully familiar with:
```
BR2_PACKAGE_WPEFRAMEWORK_COMPOSITOR_OUTOFPROCESS=y
BR2_PACKAGE_WPEFRAMEWORK_WEBKITBROWSER_TRANSPARENT=y
BR2_PACKAGE_WPEFRAMEWORK_WEBKITBROWSER_THREADEDPAINTING="2"
BR2_PACKAGE_WPEFRAMEWORK_APPS=y
```
- standard has:
```
BR2_PACKAGE_WPEFRAMEWORK_VIRTUALINPUT=y
BR2_PACKAGE_WPEFRAMEWORK_DHCPSERVER=y
```

You can study WPEFramework [here](https://github.com/WebPlatformForEmbedded/WPEFramework/tree/master/doc) and its plugins [here](https://github.com/WebPlatformForEmbedded/WPEFrameworkPlugins).

**Comment by SamDecrock** [comment]
Thanks for the explanation
