### ISSUE TITLE
WPEWebKit browser feature support list

### ISSUE THREAD

**Issue by bdirito** [Metrological/WebKitForWayland#605]
What front end rendering technologies does this project support? In developing a web page to be displayed on WPEWebKit the page is not rendering correctly. I assume this is due to missing support for some of the css (ie. no flexbox support?) 

As there is no caniuse entry for WPEWebKit is it possible to say something like the renderer was forked from the same version of webkit Safari 4 (or whatever) was built from. Thus I would be able to use 'Safari 4'  as a proxy id to ensure i transform the js & css into something that is supported by WPEWebKit.

**Comment by aperezdc** [comment]
@bdirito Flexbox is definitely supported in WPE WebKit, for example I just tested [the flexbox.help demo](https://flexbox.help/) in Cog:

![Flexbox demo in Cog](https://user-images.githubusercontent.com/723451/58627355-b5261300-82df-11e9-9ffc-36ec76afa34b.png)


If you want to use [caniuse.com](https://caniuse.com) as guidance, for latest [official releases](https://wpewebkit.org/release/) of WPE WebKit (2.24.x currently) you can use use the column for the latest Safari version that is *not* Tech Preview (“TP”). Another option for development is testing your HTML/CSS using a WebKitGTK-based browser (like [GNOME Web](https://wiki.gnome.org/Apps/Web/) or [Midori](https://www.midori-browser.org/)) on a desktop computer, because the feature of the GTK and WPE WebKit ports is the most similar. In general of your content renders well in a WebKitGTK-based browser, it will work fine with WPE WebKit as well.

I hope this helps!

**Comment by laureProthais** [comment]
@aperezdc Your answer helps me a lot thank you. 

I would just like some additional information. I develop displayed web pages for WPEWebKit in version 2.22 ... can I also be based on the canIuse compatibility of the latest Safari version in 14 ?
The rendering test via Midori interests me but unfortunately I do not know which version used in connection with WPEWebKit in version 2.22. Can you help me ? 

Thank you so much

**Comment by akvadrako** [comment]
I am trying to figure out what version of WPEWebKit (and WebKitGTK) will support the async clipboard API like `navigator.clipboard.read()`. I've tried looking through the trac history and Changelog but it's not very clear. Is there someway to find this out?

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
