### ISSUE TITLE
Help to run a web page that will communicate with GPIO.

### ISSUE THREAD

**Issue by dan-developer** [Metrological/WebKitForWayland#659]
I want to run a remote web page with wpe kit. This web page must communicate with gpio da raspberry. Via AJAX and a server running on the raspberry listening to a port, or a link between the web page and gpio.

Is that possible? Can you help me by saying where I put the part that works with gpio to compile the image?

**Comment by calvaris** [comment]
I don't know what you mean exactly:

1. A website with the server elsewhere that is being rendered in the RPI and you want the browser to do some operation with the GPIO ports of the RPI. That is not possible as the current spec does not take that possibility into account. You would have to modify WebKit in an unofficial way to enable some API that could access natively to the GPIO ports, which does not look like the best option to me.

2. You browse something that is served from that RPI from elsewhere. The broswser would then be running on your desktop, phone or whatever. You need to investigate that then from the program that is running on the server, nothing to do with the browser.

With any of the options I have to close the issue because 1 is not an option and 2 is not our scope.
