### ISSUE TITLE
Google DAI doesn't work with latest HLS.js

### ISSUE THREAD

**Issue by emutavchi** [Metrological/WebKitForWayland#673]
The simple test case causes a playback stall on first ad https://github.com/googleads/googleads-ima-html5-dai/tree/master/hls_js/simple 

GST MSE logs suggest that player creates a new track for the ad:
```
connectDemuxerSrcPadToAppsinkFromAnyThread: Only one stream per SourceBuffer is allowed! Ignoring stream 2 by adding a black hole probe.
```

tested with wpe-2.22 at 686cd2f7df, and gst 1.16.2.

**Comment by eocanha** [comment]
I've found that a new (second) pad is created by the video demuxer in the append pipeline and the old existing first pad is removed shortly after, but for a while two pads exist. That's what's causing the warning and all the data produced by the second pad (the advertisement video) to be ignored, because we only support one pad (track) per sourcebuffer in the current implementation.
I'm looking into why qtdemux behaves like that.

**Comment by eocanha** [comment]
Looks like at this point it's unavoidable that qtdemux creates a new pad. It can't reuse the old stream and associated pad because the stream id of the old video and the stream id of the advertisement are different (there's code to reuse the stream/pad if they are the same).
I'm now working on a way to detect this scenario from the AppendPipeline code and reconnect the new pad to the rest of the AppendPipeline pipeline downstream (optional parser and appsink) when the old stream/pad (from old video) is removed and only the stream/pad from the advertisement remains.

**Comment by eocanha** [comment]
I have code (not pushed yet) to reconnect the single remaining qtdemux pad to the rest of the downstream elements of the AppendPipeline. It's working fine on wpe-2.22 here and the advertisement-movie-advertisement-movie transitions work. I'd like to get it properly working upstream too (there are problems there) before pushing it.

**Comment by eocanha** [comment]
This has been fixed in commit https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/28c21c30d1fdfa93122e96e36acd36af7838fe06 on wpe-2.22 and also upstream, on https://bugs.webkit.org/show_bug.cgi?id=216039
