### ISSUE TITLE
WPEWebProcess SIGUSR1 crash in ResourceLoadObserver::shared()

### ISSUE THREAD

**Issue by Gavriliuk** [Metrological/WebKitForWayland#683]
Hi @woutermeek,

Sometimes we receive **SIGUSR1** crashreports with a callstack like the following:

Id | # | module | function | source | line | addr
-- | - | - | - | - | - | -
0|0|libWPEWebKit-0.1.so.2.2.1|shared|WebCore/loader/ResourceLoadObserver.cpp|53|0x0
0|1|WPEWebProcess|__start|||0x178
0|2|libgcrypt.so.20.1.3||||0x3df8

File **WebCore/loader/ResourceLoadObserver.cpp** contains the following function definition on the line **53**
```cpp
ResourceLoadObserver& ResourceLoadObserver::shared()
{
    static NeverDestroyed<ResourceLoadObserver> resourceLoadObserver;
    return resourceLoadObserver;
}
```

According to the log it happens during the WPEWebProcess initialization

Could you please comment whether this is a known issue?

Thanks

**Comment by vdinak240** [comment]
We have also received this similar crash in cisco g8 device with wpe 2.22

Attaching the stack trace

`Operating system: Linux
                  0.0.0 Linux 4.1.51-1.19 #1 SMP Sun Dec 13 23:47:50 UTC 2020 mips
CPU: mips
     2 CPUs

GPU: UNKNOWN

Crash reason:  SIGUSR1
Crash address: 0x75638b6c
Process uptime: not available

Thread 0 (crashed)
 0  libWPEWebKit-0.1.so.2.2.1!WebCore::ResourceLoadObserver::shared() [ResourceLoadObserver.cpp : 53 + 0x0]
 1  WPEWebProcess + 0xb98
 2  libgcrypt.so.20.1.3 + 0x3df8
 3  ld-2.24.so!__start + 0x4c`

**Comment by woutermeek** [comment]
@Gavriliuk @vdinak240 is there a way we can reproduce this in our side, or is it random?

**Comment by Gavriliuk** [comment]
Unfortunately not

The issue is intermittent and is being observed rarely during mass testing

**Comment by woutermeek** [comment]
@guijemont do you happen do have an idea what this could be?

**Comment by magomez** [comment]
The default behavior of a process when it receives a SIGUSR1 signal is exiting. Inside JSC, SIGUSR1 is used to suspend/resume garbage collection threads, but it's setting appropriate handlers for the signal. We don't think that this usage is the one causing the crash. We suspect that there might be another component/process sending SIGUSR1 signals to the WebPRocess, and that's causing the crash.

I've just pushed 4b4ab25a6bae7bca1d6b93f8cd015e3eb313d40d to the wpe-2.22 branch so JSC stops using SIGUSR1 and use SIGPWR instead. This way we can discard whether the problem comes from other process (still a SIGUSR1 signal) or from our own (a SIGPWR signal). Please give it a test and report your findings.

If the signal comes from our own process, then there's probably an usage of the signal before the JSC system is properly initialized. It would be awesome if we could get more information about what other threads are doing when the crash happens as well, so we can detect what's really happening there.

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
