### ISSUE TITLE
WPE WebKit build issue on ubuntu 16.04

### ISSUE THREAD

**Issue by harishvk1977** [Metrological/WebKitForWayland#707]
Just followed all instructions from https://github.com/WebPlatformForEmbedded/WPEWebKit on ubuntu 16.04 virtualbox amd64, initial issue was libXML missing... which i installed using cap and then got into this issue.

Already this issue raised once under "issues" but the solution is not very clear, i mean what worked.

One of the solution is to comment some patches..which i think is the not the right way.. please suggest.

-thanks
harish

*** Applying patch gst-plugins-good-0001-qtdemux-Do-not-run-the-preferred-decryptor-context-q.patch *** [17/34]
patch -p1 < "/home/harish/WPE/WPEWebKit/Tools/gstreamer/patches/gst-plugins-good-0001-qtdemux-Do-not-run-the-preferred-decryptor-context-q.patch"
patching file gst/isomp4/qtdemux.c
Hunk #1 succeeded at 7854 (offset -202 lines).
*** Applying patch gst-plugins-good-0002-qtdemux-Do-not-unref-a-NULL-stream_tags.patch *** [17/34]
patch -p1 < "/home/harish/WPE/WPEWebKit/Tools/gstreamer/patches/gst-plugins-good-0002-qtdemux-Do-not-unref-a-NULL-stream_tags.patch"
patching file gst/isomp4/qtdemux.c
Hunk #1 succeeded at 2518 (offset -82 lines).
*** Applying patch gst-plugins-good-0003-qtdemux-Clarify-field-name-about-stream-encryption-s.patch *** [17/34]
patch -p1 < "/home/harish/WPE/WPEWebKit/Tools/gstreamer/patches/gst-plugins-good-0003-qtdemux-Clarify-field-name-about-stream-encryption-s.patch"
patching file gst/isomp4/qtdemux.c
Hunk #1 succeeded at 7857 (offset -239 lines).
Hunk #2 succeeded at 7888 (offset -239 lines).
Hunk #3 succeeded at 7913 (offset -239 lines).
Failed to build WPE port dependencies with jhbuild
Died at Tools/Scripts/update-webkitwpe-libs line 25.

**Comment by eocanha** [comment]
I'm not sure if those instructions in the README are accurate anymore to build this version of WebPlatformForEmbedded/WPEWebKit on a regular desktop. To start with, the state of those jhbuild patches has been1 likely unmaintained since wpe-2.22 was forked from upstream.

If you want to try this version of WPE, I would suggest to build it for a Raspberry Pi using buildroot following instructions from https://github.com/WebPlatformForEmbedded/buildroot. I personally use the raspberrypi3_wpe_ml_defconfig configuration for internal Metrological work (that one depends on private repositories, so won't work for you), but the [raspberrypi3_wpe_defconfig configuration](https://github.com/WebPlatformForEmbedded/buildroot/blob/master/configs/raspberrypi3_wpe_defconfig) should work for everybody too.

If you want to try WPE on a regular Linux desktop, you'll have more chances to succeed if you use the upstream WPE version directly. [Get the code and follow the build instructions from here](https://trac.webkit.org/wiki/WPE#BuildingWPEWebKitfromgit).

In any case, here's a disclaimer: This answer is just based on my way of working with this repository. Maybe somebody is actually maintaining the jhbuild patches and I'm not aware.

**Comment by harishvk1977** [comment]
ok thanks for your comment.

**Comment by harishvk1977** [comment]
i have a Raspberry Pi4.. does the above RPI3 work on RPI4 also?

**Comment by eocanha** [comment]
I haven't tried it myself, but I believe there are big chances of getting it working. There's also a raspberry4_defconfig, but looking at the log of its changes in the repository, I don't think it's ready for WPE (maybe @pwielders knows). Better try raspberrypi3_wpe_defconfig.

**Comment by harishvk1977** [comment]
Built WPE on ubuntu 20.04 using https://trac.webkit.org/wiki/WPE#BuildingWPEWebKitfromgit on virtualbox. i had to allocate couple of CPU's and 12GB ram to get release version built after 4-5 hours. Debug build didn't get built, has some build issues.

**Comment by eocanha** [comment]
It's surprising that it even built with less than 16GB of RAM. Debug shouldn't be able to link the binaries with so little RAM. Anyway, debug isn't very useful on a real Raspberry Pi (at least model 3) because it's too slow and takes too much RAM.
About building, It takes (I think) less than 3 hours on my laptop (no virtual machine) with 6 cores (12 threads) and 64 GB of RAM. Fortunatelly I only have to do a full build every some weeks, and incremental builds take only a few minutes if the changes in the code are small.

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
