### ISSUE TITLE
Revoked certificate URL is not blocked by Webkit

### ISSUE THREAD

**Issue by nrajan002c** [Metrological/WebKitForWayland#708]
Website which has the revoked certificate to be blocked by browser. But Webkit browser is not blocking the URL and it launches.

URL: https://revoked.badssl.com

Note: I tried this URL in Upstream GtkWebkit as well. It is not blocked.
          But the desktop chrome blocks it properly.

Could you please check it.

**Comment by woutermeek** [comment]
We don't support certificate revocation. In order to check whether a certificate has been revoked, we need to check with several certificate providers, something that delays navigation a lot. One option to avoid this is to have some kind of periodically updated local list of rekoved certs and test, but that list could potentially be quite big.
