### ISSUE TITLE
[MSE] Assertion error on restart (`play()` called while playback on EOS)

### ISSUE THREAD

**Issue by Scony** [Metrological/WebKitForWayland#715]
hi,
when the playback ends and end of stream is marked on `MediaSource`, the gstreamer pipeline state is being changed from `PLAYING` to `READY` due to EoS (`MediaPlayerPrivateGStreamerMSE.cpp`).

Given the player in state above, when `play()` method is called on media element, then internal `seek` to `0.0` causes pipeline state change from `READY` to `PAUSED`  [(MediaPlayerPrivateGStreamerMSE.cpp#L327)](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp#L327) and thus `source-setup` signal is being emitted. It in turn causes [MediaSource.cpp#L107](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/Modules/mediasource/MediaSource.cpp#L107) assertion failure.

To me it looks like such scenario is basically not implemented.

You can check it on chrome/ff using simple, extended W3C demo: https://scony.github.io/stb-lab/mse-video-restart-auto/index.html

**Comment by eocanha** [comment]
You're right. It's currently not possible due to some limitations in that version of the MSE implementation.

However, @ntrrgc has recently landed [an MSE refactoring upstream (bug 225192)](https://bugs.webkit.org/show_bug.cgi?id=225192) that allows that use case. Unfortunately, it's not a kind of patch that can easily be backported, but when we eventually update to a new WPE version the change will be there.

**Comment by Scony** [comment]
Ok, thanks. That's good news.

**Comment by Scony** [comment]
Fixed by https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/5a819a57c0766ae50bb1792ccb2e73c587fcbd2c
