### ISSUE TITLE
Backporting rendering bugfix to wpe-2.22

### ISSUE THREAD

**Issue by Scony** [Metrological/WebKitForWayland#718]
Hi,

In `wpe-2.22` there is a bug which goes like this:

I'm using minimal repro case: [https://scony.github.io/stb-lab/css-glitch/](https://scony.github.io/stb-lab/css-glitch/)
1. When I `Select right` item, the underline (CSS border) should move from `Aus` to `An` as I change the CSS class on both elements, however, it does not happen:
![Screenshot from 2021-07-27 12-44-20](https://user-images.githubusercontent.com/1207385/127295863-a4173da9-294e-4815-88e7-45cd1833af7d.png)
2. Interestingly, when I `Focus right`:
![Screenshot from 2021-07-27 12-44-41](https://user-images.githubusercontent.com/1207385/127296070-2fb3ef25-450b-46fb-ac7e-0a1ac1e250a7.png)
3. And then `Focus left`, the underline is rendered under "An" - so it looks like I've forced re-rendering this way:
![Screenshot from 2021-07-27 12-44-53](https://user-images.githubusercontent.com/1207385/127296156-cee245b4-7e1b-4819-b741-fe31f038efcc.png)

This bug is not present in `WPE WebKit 2.28.1` (tested with `cog`).

Moreover, I know this bug was fixed in upstream between 2018-12-13 and 2019-03-28.

do you know which commit fixed that and if it would be possible to backport it to `wpe-2.22`?

**Comment by magomez** [comment]
I've been checking some versions between 2018-12-13 and 2019-03-28, and all of them fail. In the end I tested a version from 2019-04-01 that's failing as well. How did you test that the fix in inside those dates?
I've also found that I cannot reproduce the issue with 2.22 on my desktop, but it happens with the same version on the rpi. This makes finding the problem a bit harder, but I'll continue debugging the problem.

**Comment by Scony** [comment]
@magomez I've seen the issue on:
**Eolie** browser **0.9.45**, released 13.12.2018, WebKitGTK ~ 2.22.4/5
but not on:
**Eolie** browser **0.9.60**, released 28.03.2019, WebKitGTK ~ 2.24.0

so I concluded about the time range based on above.

**Comment by magomez** [comment]
I'm still investigating this issue.
I didn't find a fix in the revisions mentioned, but I found a commit that removes the issue some months after the release of 2.24. The problem is that the commit is not a fix for the issue, but a mayor change related to how the content layers are rendered. And not only it depends on several previous commits, but there are also subsequent commits that fix issues generated by it (and not all of them are easily identifiable). This makes backporting the patch quite tricky, and prone to add new glitches.

So I've been investigating what's happening there and how to fix it. Basically the divs with the Aus and An texts are pushed to their own layers, and the style change to the span is not causing a redraw because it doesn't cause a change in the size of the containing div. Adding add borders to the left and right of the span instead of just the bottom makes it render properly, or removing the padding of the containing divs, cause these changes require the layer to be resized.

I'm diving into the layout process to find why that style change doesn't trigger a redraw, cause that's definitely a bug. It's a complex code and it's taking me a while, but I hope I'll find the problem soon. I'll keep you updated.

**Comment by Scony** [comment]
Okay, thank you for update.

**Comment by magomez** [comment]
I've just pushed 154984fd4340d566d2b5494a9ad4fe137c9f50ad to the wpe-2.22 branch, which should fix the issue. Please verify that it's fixed for you as well and close this.

**Comment by Scony** [comment]
Looks very concise - should be easy to apply. Thank you! I Will test it Monday.

**Comment by Scony** [comment]
It works as expected now. Well done @magomez Thank you very much.
