### ISSUE TITLE
WPEWebProcess Crash(JavaScriptCore) due to SIGFPE

### ISSUE THREAD

**Issue by kkanag314** [Metrological/WebKitForWayland#726]
**Test Procedure**
1. Launch Pluto app though the MENU option.
2. Navigate through the app and select and play some asset.
3. Observe that web process crash due to hang.

Webprocess crashed with signature 'normalizePrototypeChain'

Crashed Url :  https://xfinity.pluto.tv?lmt=0&us_privacy=1-N-

WPE commit : **22d6522031250cdeb967101a0fa0cc91f190b84d**

Crash Details:

```
[ 00 ] normalizePrototypeChain
[ 01 ] llint_slow_path_put_by_id
[ 02 ] 0x765aa330
[ 03 ] _fini
[ 04 ] call
[ 05 ] boundThisNoArgsFunctionCall
[ 06 ] 0x765a4b60
[ 07 ] _fini
[ 08 ] _fini
[ 09 ] profiledCall
[ 10 ] handleEvent
[ 11 ] fireEventListeners
[ 12 ] fireEventListeners
[ 13 ] dispatchEvent
[ 14 ] call
[ 15 ] dispatchFunctionsFromMainThread
[ 16 ] _FUN
[ 17 ] g_main_context_dispatch
[ 18 ] g_main_context_iterate
[ 19 ] g_main_loop_run
[ 20 ] run
[ 21 ] ChildProcessMain<WebKit::WebProcess, WebKit::WebProcessMain>
[ 22 ] __libc_start_main
[ 23 ] __start
```

**Comment by SameeAnsar** [comment]
The crash happened due to some RACE condition , we weren’t able to get the exact steps for reproduction.
Recent Observation on the hang crash:
The crash happen to older MIPS-based boxes almost exclusively. MIPS boxes usually have high load average(but it not extremely high) upon the crash and not so much free memory (30-40K).
Some hangs crash information contain indication that GC were running.
Also, there are data underflow indications preceding the hang.
Kindly help us  regarding this.

Thanks
Alsameema

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
