### ISSUE TITLE
CSS transition timing curves executed twice

### ISSUE THREAD

**Issue by g3t0r1x** [Metrological/WebKitForWayland#730]
Hello,

For a CSS transition timing curves (i.e. ease, ease-in, ease-out, ease-in-out) I'm observing that animation is executed twice for some reason.

Example of after transformation HTML code posted below:
```
<html>
    <head></head>
        <div style="position: block" id="interventionArea"></div>
        <div style="position: block; right: 0; top: 100; width: 960px; height: 540px; outline: green solid 5px" id="renderArea">
            <div style="width: 600px; height: 100px; position: relative;">
                <div style="width: 100px; height: 100px; background-color: rgb(255, 0, 0); position: absolute; left: 500px; transition: left 500ms cubic-bezier(0.3, 0.1, 0.6, 0.15) 0s;"></div>
            </div>
        </div>
    </body>
</html>
```

I managed to find using bisect strategy on webkit repository that this commit is fixing my issue: https://github.com/WebKit/WebKit/commit/7dda3aa8057571b1a345b90c21861d333ad2759c#diff-9d5c3f8d15ecbd7344c7bfd9be9bcb453345caa45d73a4ee3c3462cad5c46ff9

However once I've added that to my WPE-WebKit (2.22) it doesn't do the trick.

Could someone take care of that?

**Comment by magomez** [comment]
The commit you found is not a fix for the problem itself. It enables WebAnimations, which is a new implementation to handle animations, which is not present in 2.22. That's why cherry-picking it didn't work. In order to use that commit we would need to backport the complete WebAnimations implementation, which is not that easy.

Instead, I'll try to fix the issue in the animations code in 2.22. I'll let you know when I have a fix.

**Comment by magomez** [comment]
I'm trying to reproduce the issue but I'm not able to see any duplicated animation. I've picked the code you posted and modified it a bit so the left property of the element with the transition is set to 0xp 1 sec after the page load, and I can see the transition working fine (using cubic-bezier, ease-in, ease-out and ease-in-out). This is the code that I have:

```
<html>
  <head></head>
  <body>
    <div style="position: block" id="interventionArea"></div>
    <div style="position: block; right: 0; top: 100; width: 960px; height: 540px; outline: green solid 5px" id="renderArea">
      <div style="width: 600px; height: 100px; position: relative;">
        <div id="animated" style="width: 100px; height: 100px; background-color: rgb(255, 0, 0); position: absolute; left: 500px; transition: left 500ms cubic-bezier(0.3, 0.1, 0.6, 0.15) 0s;"></div>
      </div>
    </div>
    <script>
         setTimeout(function() {
             var div = document.getElementById("animated");
             div.style.left="0px";
         } , 1000);
    </script>
  </body>
</html>
```

Could you provide a test that reproduces the issue for you so I can test it? Also, which is the exact revision of wpe-2.22 that you're using?

**Comment by jhowg97** [comment]
Hi,
I believe the test beign referenced is the following:
https://certification.bbctvapps.co.uk/act/test/ui/36/css-supports-transition-timing-curve/payload.js
https://certification.bbctvapps.co.uk/act/test/ui/36/css-supports-transition-timing-curve/index.html

**Comment by magomez** [comment]
That's weird, that test runs fine for me on the desktop. It may be a thing specific to some architecture. Which one are you using? mips? arm? I'll do some platform testing in the meanwhile to see if I can reproduce the problem.

**Comment by jhowg97** [comment]
Yeah it's an arm platform

**Comment by magomez** [comment]
I've been able to reproduce the issue on the rpi3.
What happens here is not that the animations are duplicated, it's just that the test is testing some of the animations twice, and that's why you see some animations being repeated.

From what I saw in the test code, it tests 6 animation curves (linear, ease, ease-in, ease-out, ease-in-out and a cubic-bezier). It launches each animation and uses requestAnimationFrame to compare in several points the real position of the animation against the value it should have. As this doesn't have to match exactly, there's a margin error in the code of 0.02. On the desktop, this works, and each test is only run once (so 6 animations are seen).

On the rpi, on the other hand, only the linear and ease-in test pass and the rest fail, so each of them is retried once. This means that there are 10 animations visible, 2 of them once (linear and ease-in) and 4 of them twice (ease, ease-out, ease-in-out and cubic-bezier). So this explains why the animations seem duplicate, despite they aren't.

Then the question is why some of the tests fail. The animation positions are calculated based on the time passed since the animation started. But this time passed is calculated in two different poins: once inside wpe when calculating the animation progress and once inside the test code to predict the desired animation position. These two measures won't produce the exact same result as they are taken in slightly different moments in time. The more powerful the machine running wpe, the faster the execution, and the closer the measures are, which causes the calculated values of the animation in both times to be more similar (and that's why the test passes on the desktop). But on slower hardware, the time measures differ a bit more, so the difference between the expected and real animation positions increases, causing the difference to be bigger than the 0.02 error margin. I've tested that on the rpi it's enough to increase the error margin to 0.05 and then the test starts passing. Depending on the performance of your board, you may need to set a bigger value to make the test pass there as well.

All in all, this seems to be a problem with how the test is designed and not a problem in wpe, as I've cheked that the different animation curves are working properly.
