### ISSUE TITLE
CSS radial-gradient() not working correctly

### ISSUE THREAD

**Issue by g3t0r1x** [Metrological/WebKitForWayland#732]
Hello,

`radial-gradient()` CSS function should work as per documentation below:
https://drafts.csswg.org/css-images/#radial-gradients

The most interesting part:

```
<ending-shape>
    Can be either circle or ellipse; determines whether the gradient’s ending shape is a circle 
    or an ellipse, respectively. If <ending-shape> is omitted, the ending shape defaults to a circle if
    the <size> is a single <length>, and to an ellipse otherwise. 
```

So default shape (if none provided) should be ellipse. However on WPEWebKit-2.22 circle is seen instead.

I have checked with WPEWebKit-2.28, where ellipse is correctly rendered.

Code example below:
```
<html>
    <head></head>
    <body>
        <div style="display: block; right: 0; top: 100; width: 960px; height: 540px; outline: green solid 5px" id="renderArea">
            <div style="background-color: white; color: black; height: 100%;">
                <h3 style="display: inline-block; margin-left: 10px; padding: 0px; font-size: 18px;">Actual</h3>
                <div style="height: 160px; width: 760px; margin: 5px; background-image: radial-gradient(red 5%, yellow 15%, green 60%);"></div>
                <h3 style="display: inline-block; margin-left: 10px; padding: 0px; font-size: 18px;">Expected</h3>
                <div><img src="expected.png" style="display: inline-block; margin: 5px; vertical-align: top;"></div>
            </div>
        </div>
    </body>
</html>
```
`expected.png` attached to this ticket. 
![expected](https://user-images.githubusercontent.com/44023152/135317691-f6a67686-4519-47fb-8978-ba4f66058dd0.png)

I did some investigation regarding this on WebKit repository side. I managed to find one promising commit: https://github.com/WebKit/WebKit/commit/bd540ecdd2e0fe70a4240476bf9b51bc94497888, but it seems to be back-ported to WPEWebKit already.

**Comment by magomez** [comment]
I've just tested the wpe-2.22 branch and the output is the expected one. I've worked on this a while ago and fixed it upstream (with the commit you mention), and then backported to fix to the wpe-2.28 and wpe-2.22 branches. So yes, this should be already working on the wpe-2.22 branch. This issue was handled on https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/719

I'm not sure in which revision are you in the wpe-2.22 branch but, can you check whether it includes commit aea55f8abae1b72dde4ed0d3c521de70561c8e65 which is the fix for this? If you don't have it, please cherry-pick it and close this issue if it works as expected.
