### ISSUE TITLE
Screen is flashing while navigating within the app

### ISSUE THREAD

**Issue by przemyslaw-gorszkowski-red** [Metrological/WebKitForWayland#768]
When we navigate within the app (https://c5apps-staging.channel5.com/my5virginhorizon/index.html) , we can observed flushing of the screen (for a milliseconds we can see a blue screen).

This issue is observed on WPE 2.22(RaspberryPi 3 B+) and also 2.30(Gnome Web on PC )
The issue is not reproduced on Chrome or Firefox.

This is the recording of the problem:
https://user-images.githubusercontent.com/47318228/149286136-1ddc7f5a-261f-4a68-8c1d-e6865014b42e.mov

**Comment by magomez** [comment]
@przemyslaw-gorszkowski-red, is there any test account that I could use to browse the app? if that's not the case, can I create a free account or do I need anything special? 

On a first look to the video my bet is that the blue that you're seeing is something that's behind the image, that becomes visible for a moment while the image is loaded. But there seems to be a fade-out/fade-in effect as well when showing a new image (or maybe it's an effect of the video being played at very low speed), so I can't be sure.

**Comment by przemyslaw-gorszkowski-red** [comment]
@magomez to see the problem you don't need to create any account(just select option "Not now")

**Comment by magomez** [comment]
The problem here is related to the asynchronous decoding of large images (that is also affecting https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/773). When a new background image needs to be loaded, it's scheduled for decoding in a secondary thread, and while it's not ready, nothing is painted. This causes that, when the previous image is removed, there's a moment where the blue background is visible (the new image is not painted because it's not ready yet), and when the image has finished decoding it gets shown.

While async decoding of large images is usually an advantage, as it makes the rendering faster and UI more responsive, in this case it's causing a glitch. Ideally the app should have some background color to avoid the content below it becoming visible. But I guess we don't have control of the app, so for this case we could disable the async decoding. As we don't want to disable that feature for a general case, I'm going to create a patch that disables the feature if some env variable is defined.

**Comment by magomez** [comment]
Ah, I've just realized that there's already a setting to disable the async decoding of large images (WKPreferencesSetLargeImageAsyncDecodingEnabled). This is a better option than the env var, as it allows enabling and disabling it on demand, but I'm not sure whether you have access to the launcher code (are you using WPEFramework/Thunder?).

If you can tweak the launcher, it would be better if you can just enable/disable this setting as needed. But if you prefer the env var, I can add that change to WPE. What do you think @przemyslaw-gorszkowski-red ?

For testing purposes, this is the patch that disables async decoding when the env var WPE_DISABLE_ASYNC_DECODING_LARGE_IMAGES is defined. Please give it a test, and confirm that it fixes the issue for you. Also, please, check whether this mitigates a bit the issue in https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/773. It's not going to fix it, as we can't avoid some thumbnails being black for a moment, but it might make it a bit less visible.

```
diff --git a/Source/WebCore/rendering/RenderBoxModelObject.cpp b/Source/WebCore/rendering/RenderBoxModelObject.cpp
index d0ffc3354c4b..65f4d313ec8a 100644
--- a/Source/WebCore/rendering/RenderBoxModelObject.cpp
+++ b/Source/WebCore/rendering/RenderBoxModelObject.cpp
@@ -350,6 +350,14 @@ bool RenderBoxModelObject::hasAutoHeightOrContainingBlockWithAutoHeight() const
 
 DecodingMode RenderBoxModelObject::decodingModeForImageDraw(const Image& image, const PaintInfo& paintInfo) const
 {
+    static bool largeImageAsyncDecodingDisabledByEnvVar = false;
+    static bool largeImageAsyncDecodingDisabledByEnvVarInitialized = false;
+
+    if (!largeImageAsyncDecodingDisabledByEnvVarInitialized) {
+        largeImageAsyncDecodingDisabledByEnvVar = !!getenv("WPE_DISABLE_ASYNC_DECODING_LARGE_IMAGES");
+        largeImageAsyncDecodingDisabledByEnvVarInitialized = true;
+    }
+
     if (!is<BitmapImage>(image))
         return DecodingMode::Synchronous;
     
@@ -376,6 +384,8 @@ DecodingMode RenderBoxModelObject::decodingModeForImageDraw(const Image& image,
         return DecodingMode::Synchronous;
     if (paintInfo.paintBehavior.contains(PaintBehavior::Snapshotting))
         return DecodingMode::Synchronous;
+    if (largeImageAsyncDecodingDisabledByEnvVar)
+        return DecodingMode::Synchronous;
     if (!settings().largeImageAsyncDecodingEnabled())
         return DecodingMode::Synchronous;
     if (!bitmapImage.canUseAsyncDecodingForLargeImages())
```

**Comment by rychem** [comment]
@magomez many thanks for analysis and patch. We will perform testing.
Since switch from async to sync method will be global (not per specific application/page), what are potential drawbacks of this method? It was probably introduced to solve some other category of issues ... what could it be?

**Comment by magomez** [comment]
> @magomez many thanks for analysis and patch. We will perform testing. Since switch from async to sync method will be global (not per specific application/page), what are potential drawbacks of this method? It was probably introduced to solve some other category of issues ... what could it be?

In order to render an image, it was to be decoded into a bitmap first. The time required for this isn't usually huge but, if the image is big, it can take a noticeable amount of time. Before this change, the main thread would block until the decoding operation was over, which means that JS won't be executed, the rendering of the page would stop, and no events would be handled. The change causes the decoding to happen in a secondary thread, which leaves the main thread free to continue performing actions. The drawback is that there's some time when we don't have the image content to render, and at those points nothing is rendered where the image should be.

**Comment by rychem** [comment]
@magomez proposed change is improving rendering performance for this and https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/773 issues.
We are still checking it against potential regressions/side effects. When none found we will be able to close those tickets.
Thanks for support.

**Comment by przemyslaw-gorszkowski-red** [comment]
@magomez probably WKPreferencesSetLargeImageAsyncDecodingEnabled has to be moved to public API from the private one (we use WPEFramework/Thunder). I can move it. The other option can be also add this option with env var WPE_DISABLE_ASYNC_DECODING_LARGE_IMAGES.

Once again many thanks for your support here. and in #773 ticket.

**Comment by przemyslaw-gorszkowski-red** [comment]
<< But if you prefer the env var, I can add that change to WPE.
@magomez I prefer to have it as env var, will you create a change for it or should I do it?

**Comment by magomez** [comment]
>  @magomez I prefer to have it as env var, will you create a change for it or should I do it?

I've just pushed commit 48aa792b6d9b8bdd21cbda7825013f439fb82866 to the wpe-2.22 branch with the env var.
