### ISSUE TITLE
WPE 2.22 - Rendering thumbnails/images/keyframes problem during fast forward

### ISSUE THREAD

**Issue by przemyslaw-gorszkowski-red** [Metrological/WebKitForWayland#773]
The problem with blinking black thumbnails/keyframes can be observed during fast forward on youtube.com/tv service (but not only, it is also observed on other services where the thumbnails are displayed  during FF and the playback is played in background). The fast forward is done by keeping down the key responsible for FF (right arrow in case of RPI).

The problem is seen on WPE 2.22. 
The recording with the problem: 
https://user-images.githubusercontent.com/47318228/152759119-48e2a99f-e99f-46d3-a2cc-b8e693cbbd47.mp4

To start the youtube.com/tv service the UA has to be changed to: "Mozilla/5.0 AppleWebKit (KHTML, like Gecko)"

The handling of the thumbnails(keyframes) are done on UI side (JavaScript code of the application). Ihe app downloads some image on which there are multiple small images with that key frames which are displayed during FF.

Example of such image with group of thumbnails/keyframes in case of YTTV downloaded from : https://i.ytimg.com/sb/YE7VzlLtp-4/storyboard3_L2/M0.jpg?sqp=-oaymwGbA0g48quKqQOSA4gBAZUBAAAEQpgBMqABPKgBBLABELABDbABDLABELABFbABH7ABJrABLbABDrABDrABD7ABErABF7ABK7ABLLABKbABD7ABDrABELABFbABH7ABKrABMrABKbABD7ABEbABFLABGLABJrABPbABOLABLbABEbABFLABHrABKrABMbABS7ABR7ABNrABFbABHLABKbABLrABObABR7ABTbABP7ABJbABLrABN7ABPbABR7ABUrABUbABRbABM7ABQLABQrABQ7ABTLABRLABRrABQ7gBEbgBEbgBFbgBI7gBRLgBQ7gBQ7gBQ7gBEbgBE7gBFrgBL7gBQ7gBQ7gBQ7gBQ7gBFbgBFrgBKbgBQ7gBQ7gBQ7gBQ7gBQ7gBI7gBL7gBQ7gBQ7gBQ7gBQ7gBQ7gBQ7gBRLgBQ7gBQ7gBQ7gBQ7gBQ7gBQrgBQrgBQ7gBQ7gBQ7gBQ7gBQ7gBQrgBQrgBQrgBQ7gBQ7gBQ7gBQ7gBQrgBQrgBQrgBQrgBQ7gBQ7gBQ7gBQrgBQrgBQrgBQrgBQqLzl_8DBgjA86P5BA==&sigh=rs%24AOn4CLDJUYmnVmAsv5lps1Je3f8aYAyjkA

**Comment by rychem** [comment]
@woutermeek, according to recommended flow, the issue is cloned from RDK-505

**Comment by magomez** [comment]
I gave it a look and this is what's happening:

- Keeping the forward button press generates a forward event several times per second. Also, if kept pressed, the interval advanced in the video will grow (for example 10 seconds at first, then a minute, then 2 minutes).
- As mentioned, the thumbnails are loaded as an image (let's call it set), that contains several thumbnails (the number can vary, I've seen up to 100, I guess it depends on the video). This set has a size of 800x450, a quite big image.
- Every time we need to show a thumbnail from a new set, we need to load and decode the image, which takes time. Due to this, the first image of a set that is displayed can be black for a moment (black is the background color of the container div). If we stopped the forward seek at that point, the thumbnail would be properly shown after a moment of black. Subsequent thumbnails in the same set would be properly displayed immediately because the set is already loaded and decoded. This is why at some points we can see black thumbnails for a moment. And I'm afraid this is not avoidable, and it's more noticeable the less powerful is the hardware. You can check that this issue doesn't (or hardly) reproduce going backwards, because the images are already in the cache and they don't need to be reloaded.
- Something a bit more serious happens if we keep pressing forward and the advanced interval starts growing. We can get to a point where each thumbnail shown is stored in a different set, so all of them are black for a moment. But the forward events can happen faster than the thumbnail is drawn, moving to a new thumbnail before the previous one was shown. This causes that the thumbnails appear to be always black, because we can't download, decode and show them before the next one is requested. If the fast forward is stopped, the appropriate thumbnail is properly loaded and stops being black.

Given this scenario, I don't think there's much the browser can do to fix this. We can't void the load and decode stages, and if the user is requesting a new thumbnail before the browser is able to show the current one there's nothing we can do. What comes to my mind is reducing the amount of forward events that are generated per second. That would alleviate the problem because the browser has more time to present the thumbnail, but it won't avoid the brief black blink at the beginning of each set. Having sets of smaller size would also help, as the time needed to load and decode them would be smaller.

**Comment by przemyslaw-gorszkowski-red** [comment]
<< What comes to my mind is reducing the amount of forward events that are generated per second.

But it can be done rather on app side right? if we do it on our side then it affects all other apps/sites

**Comment by magomez** [comment]
> << What comes to my mind is reducing the amount of forward events that are generated per second.
> 
> But it can be done rather on app side right? if we do it on our side then it affects all other apps/sites

Yes, it should be done on the app side.

**Comment by rychem** [comment]
@magomez thanks for your comment.
Issue was reported with reference to YT application, however oryginally issue is observed on BBC iPlayer app (which cannot be run on RPI, that is why we used YT for issue description).
However, for both cases, YT and BBC, it is hardly to imagine that Vendor adapts his application for one Customer. Especially that most valid argument is that rendering issues were not observed (or not on such big scale) on legacy browser.
It is visible regression of rendering performance, thus we cannot push it over towards app vendor.

**Comment by magomez** [comment]
> @magomez thanks for your comment. Issue was reported with reference to YT application, however oryginally issue is observed on BBC iPlayer app (which cannot be run on RPI, that is why we used YT for issue description). However, for both cases, YT and BBC, it is hardly to imagine that Vendor adapts his application for one Customer. Especially that most valid argument is that rendering issues were not observed (or not on such big scale) on legacy browser. It is visible regression of rendering performance, thus we cannot push it over towards app vendor.

I understand when you mention the legacy browser, you mean the 2017 branch of WPE. I'm pretty sure that the black flashes when requesting a thumbnail from a new set are happening there as well, as the way WPE renders the images is basically the same, and the time required to get and decode the image can't be reduced.

Now, depending on the point of the 2017 branch you were using, async decoding of large images may or may not have been enabled. I'm going to guess that it was disabled, and that could maybe mitigate a bit the black flashes (again, they will be still there, maybe a bit less frequent or for a shorter time). In the 2.22 branch this feature is enabled, which might be making the problem more visible. You should test whether the result is acceptable by disabling this feature. As I mentioned in https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/768, this can be done by using the WKPreferencesSetLargeImageAsyncDecodingEnabled setting or by applying the patch that I pasted there and setting some value to the env var WPE_DISABLE_ASYNC_DECODING_LARGE_IMAGES.

Please let me know whether this helps.

**Comment by przemyslaw-gorszkowski-red** [comment]
@magomez thank you very much for your analysis and help. I will  test your suggestion and will let you know about the result.

You are right, by legacy browser we mean the 2017 branch of WPE.

BTW: are there any tests which can be use to measure a rendering performance?

**Comment by robsuero** [comment]
@przemyslaw-gorszkowski-red - have you had any success with the recommended change?

**Comment by rychem** [comment]
@robsuero , @magomez proposed change is improving rendering performance for this and https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/768 issues.
We are still checking it against potential regressions/side effects. When none found we will be able to close those tickets.
Thanks for support.

**Comment by przemyslaw-gorszkowski-red** [comment]
@magomez  many many thanks for your support here and in #768 ticket.

**Comment by przemyslaw-gorszkowski-red** [comment]
The problem is resolved by fix from https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/48aa792b6d9b8bdd21cbda7825013f439fb82866
