### ISSUE TITLE
WPEWebKit 2.28 with Vulkan backend

### ISSUE THREAD

**Issue by ramkumarpraba** [Metrological/WebKitForWayland#872]
Hi 
	I try to run WPEWebKit 2.28 with Vulkan backend instead of openGL . I hope using ANGLE project i can do that . Can anyone in this group kindly help me the steps to build WPEWebKit with Vulkan backend via ANGLE.

Ref : https://github.com/WebPlatformForEmbedded/WPEWebKit/tree/wpe-2.28/Source/ThirdParty/ANGLE

**Comment by magomez** [comment]
Short answer: at this moment it's not possible to use WPE with Vulkan. It requires OpenGL or GLES instead. And modifying it to use Vulkan is not an easy feat.

Long answer: by performing all the accelerated paintings through ANGLE it should be possible to just switch between different backends, being Vulkan one of them. But nowadays WPE doesn't use ANGLE for that. It's just being used for shared verification when using WebGL, but nothing else (this is currently being changed so ANGLE is used for WebGL rendering in general). But the rest of the rendering that's not WebGL doesn't (and doesn't plan to) use ANGLE. It uses direct OpenGL/GLES calls. In order to use Vulkan here, all that code should be updated to support Vulkan as well.

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
