### ISSUE TITLE
buildroot upstream and wpewebkit package

### ISSUE THREAD

**Issue by luizinhoz** [Metrological/WebKitForWayland#883]
I started at 2016 a custom project, forked from metrological/buildroot, config rpi3_wpe_defconfig with userland+wpewebkit+wpeframework.
I want to update my outdated project to supports new boards due to raspberry shortage, but I'm confused the best way to proceed.
First I cloned buildroot/buildroot and built a distro with mesa(vc4)+wpewebkit+cog+wayland.
The buildroot wpewebkit get sources from wpewebkit.org, updated version is 2.36.
But I didn`t understood why WebPlatformForEmbedded/buildroot, package wpewebkit, get sources from WebPlatformForEmbedded/WPEWebKit and seens stuck in version 2.28.
I'm glad If someone can guide me behind the official repositories so that I can keep my project updated in a better way.

**Comment by magomez** [comment]
There are 2 different repositories for wpe. There's the main upstream one, currently living in https://github.com/WebKit/WebKit, and the WebPlatformForEmbedded one, which lives in https://github.com/WebPlatformForEmbedded/WPEWebKit.

The first one is the official one, where the day to day development happens, and where the stable releases are coming from. These stable releases (currently 2.36) can be built through the upstream buildroot recipes (those in buildroot/buildroot).

Then there's the "downstream" repository for wpe that lives in WebPlatformForEmbedded/WPEWebKit. This contains some older stable branches with custom patches that are needed for some STB hardware. The branches that are currently being used there are mainly 2.22 and 2.28 (as you mention). In order to build these branches, you need the buildroot version stored in WebPlatformForEmbedded/buildroot.

So, either you use both buildroot and woe from upstream, or you use them both from WebPlatformForEmbedded. But you can't mix those.

As you are using wpeframework, you're entitled to use buildroot from WebPlatformForEmbedded, as it's not available on upstream buildroot. And once inside WebPlatformForEmbedded, the newer wpe version that you can use is 2.28 for the moment. If you don't need wpeframework, then you can use upstream buildroot and have wpe 2.36 there.

**Comment by luizinhoz** [comment]
thank you!
