### ISSUE TITLE
[2.28] Missing memory measurements in Inspector/Timelines/Memory

### ISSUE THREAD

**Issue by Scony** [Metrological/WebKitForWayland#905]
as in title, `Page`, `Layers`, and, `Images` memory measurements are missing, see:
![Screenshot from 2022-07-07 16-17-26](https://user-images.githubusercontent.com/1207385/177796783-29a3e6b3-6e8e-4fa5-a434-7e79a834c10e.png)

**Comment by magomez** [comment]
I reported this upstream, as inspector issues usually happen there, and it was handled on https://bugs.webkit.org/show_bug.cgi?id=242500. A limitation was commented there, that WPE doesn't report the memory used by image, layers and page cathegories, becase we don't gather that data. So the fix added the possibility to show the memory used by JS and a new cathegory with the memory used for non JS.

I've pushed the upstream fix to wpe-2.28.

But when I was backporting the patch, I realized that our inspector doesn't have that memory tab. I has the CPU one. So I'm not able to see those memory values, neither upstream or in 2.28, and using the normal or the HTTP inspector.

@Scony, how are able to see that memory section?

**Comment by Scony** [comment]
@magomez there is small `Edit` button bottom right to the red dot.

**Comment by magomez** [comment]
Ah, found it! Ok, the 2 categories seem to be there, one for JS memory and the other one for the page, that includes all the memory that's not JS.

**Comment by Scony** [comment]
Good, let me know once we got it in `2.28`

**Comment by magomez** [comment]
Already there! 0da3c2c144202a2302b72414e72a17abdc3d284c

**Comment by Scony** [comment]
That's good news. I'll test it Monday and close if all good. Thanks @magomez

**Comment by Scony** [comment]
Indeed it shows something. I'm assuming it's not a total memory, right @magomez?

**Comment by magomez** [comment]
There are 2 cathegories. One is the memory used by JS and the other is the memory used by everything else except JS. The total should be the sum of both.

**Comment by Scony** [comment]
@magomez what I mean the sum of the 2 is not the total from OS perspective, right? The page mentioned https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/904 reports total of ~40MB in inspector while from OS perspective it's much more, is that fine?

**Comment by magomez** [comment]
For me it's reporting ~40MB in JS, but ~100MB in the page category.
What you should ideally see is a spike to around ~240MB in the page category for a moment, and then it will go back to around ~100MB there. That spike is the one caused by the imageBacking buffers that are being created and sent to the compositor. The problem is that those buffers have a very short file, so if the memory measurement is not performed exactly at that point it, the spike won't be visible. I guess this is a problem of the way we get the amount of memory used, as we don't keep track of it, but poll the system for those values with some predefined frequency. But I guess without the code to keep track of the allocations everywhere, that's the best we can do.

**Comment by Scony** [comment]
Okay, confirmed same results on my end - on desktop. I think it's good enough for now, thanks!
