### ISSUE TITLE
[WPE-2.22] Change color scheme in CairoGlSurface

### ISSUE THREAD

**Issue by jaroslaw-bojko-red** [Metrological/WebKitForWayland#935]
ImageBufferData::createCairoGLSurface creates a texture which will be used by Cairo to render accelerated content. Cairo inside library executes glTexSubImage2D method to update the canvas with GL_BGRA_EXT parameter as color order.

According to https://registry.khronos.org/OpenGL-Refpages/es2.0/xhtml/glTexSubImage2D.xml documentation we need to use the same color order in glTexImage2D (from ImageBufferData) and glTexSubImage2D.
This commit uses GL_BGRA_EXT in glTexImage2D to use the same color order that is used in cairo.

Without the fix Cairo did not update the canvas because of mismatch in color orders between glTexSubImage2D inside cairo and glTexImage2D from ImageBufferData in Webkit.

PR with the change: https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/934

**Comment by jaroslaw-bojko-red** [comment]
Issue can be reproduce on 
[canvas_bgra.html.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/9527425/canvas_bgra.html.txt)
(change file extenstion from html.txt to .html and run file on webserver, works on: python3 -m http.server 8000)

With the fix:
Small squares change in top left corner, in order: red,gren,black.

Without the fix:
Small squares do not change the screen is still

**Comment by magomez** [comment]
I've been testing this on the rpi. As I expected (otherwise we would have had a lot of bugs prior to this), the texture created for the canvas there is GL_RGBA and everything works fine. The same happens with the desktop.

The testcase that you provided works perfectly there. The js call to putImageData triggers the creation of an intermediate cairo_surface_t that's used to paint the passed data onto the canvas texture. This intermediate surface is backed by a texture whose format is GL_RGBA (chosen by _cairo_gl_get_image_format_and_type), as the others, so the result is fine.

I'm not sure what's exactly happening on your platform. It seems that it's not selecting the same format as the other platforms. Maybe your platform is big endian?

In any case, I've created a logging patch to apply to cairo and try to find out what's happening there. I'm attaching it here. @jaroslaw-bojko-red, could you patch cairo and send me the output when running the test that you provided, please?

[cairo-log.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/9558602/cairo-log.patch.txt)

**Comment by jaroslaw-bojko-red** [comment]
@magomez Also in our reproduction the problem was not observed on rpi, or on the device with the same graphic module as rpi.

I applied the patch, two changes were not included, most probably because of the version mismatch. (on the device we have cairo 1.14.6-r0)
`patching file src/cairo-gl-surface.c
Hunk #16 succeeded at 412 with fuzz 1 (offset -2 lines).
Hunk #17 succeeded at 441 (offset -2 lines).
Hunk #18 succeeded at 458 (offset -3 lines).
Hunk #19 succeeded at 610 (offset -3 lines).
Hunk #20 succeeded at 646 (offset -3 lines).
Hunk #21 succeeded at 689 (offset -3 lines).
Hunk #22 succeeded at 716 (offset -3 lines).
Hunk #23 succeeded at 877 (offset -3 lines).
Hunk #24 succeeded at 944 with fuzz 1 (offset -4 lines).
Hunk #25 FAILED at 959.
Hunk #26 succeeded at 959 (offset -45 lines).
Hunk #27 succeeded at 972 (offset -45 lines).
Hunk #28 succeeded at 990 (offset -45 lines).
Hunk #29 FAILED at 1099.
Hunk #30 succeeded at 1089 with fuzz 2 (offset -61 lines).
`
I added a custom logs, that are similar to rejected one, [canvas.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/9607184/canvas.patch.txt)

After this I grabbed the logs from the device: [logs_no_refresh_canvas_reproduction.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/9607217/logs_no_refresh_canvas_reproduction.txt)
Logs were captured on the device that reproduces the problem with original code (wihtout the fix from the review), so the screen was still without the updates.

**Comment by jacek-skiba-red** [comment]
@magomez issue is reproducible on devices with GPU VideoCore 5 or 6. Currently only RPi 4 Model B has VideoCore VI. All others RPI use VideoCore IV.

**Comment by magomez** [comment]
> I applied the patch, two changes were not included, most probably because of the version mismatch. (on the device we have cairo 1.14.6-r0)

Ah, that explains a lot! I'm using 1.16 here. I've just given a look to the differences in cairo-gl-surface.c between those versions and 1.14 is missing the part that should force the usage of GL_RGBA and convert the image to that format. That's why on your platform it uses GL_BGRA. Please, update cairo to 1.16.0 and your problem should be gone.

If your curious, the part that's missing is inside _cairo_gl_surface_draw_image(). All the if that starts with

    if (_cairo_gl_get_flavor () == CAIRO_GL_FLAVOR_ES3 ||
	_cairo_gl_get_flavor () == CAIRO_GL_FLAVOR_ES2) {

Inside that if, the code decides that the output formats allowed are PIXMAN_a8b8g8r8 or PIXMAN_r8g8b8a8 (depending on the endianess), which are the ones that we can upload directly a GL_RGBA texture. If the format of the image that we want to paint doesn't match those formats, the require_conversion flag is set, which causes the code to create a new cairo surface with the desired format and then paint the original image into the new surface. Now that we have the image in the format we want, we can call _cairo_gl_get_image_format_and_type() and it should return GL_RGBA as we want it to.

@jaroslaw-bojko-red, please try updating cairo and tell me whether that fixes the issue.

**Comment by jaroslaw-bojko-red** [comment]
Hi @magomez I updated cairo to 1.16.0 and the problem is gone as you suspected. The canvas updates without GL_BGRA.
Thank you for the support and explanation about differences between versions.
