### ISSUE TITLE
[wpe-2.28] background flickering when using CSS transforms

### ISSUE THREAD

**Issue by Scony** [Metrological/WebKitForWayland#946]
I've recently tested ACT-1434 test case from BBC test sute on various webkit-based browsers and it looks like there are some evident problems related to the CSS transforms. In the test case - https://certification.bbctvapps.co.uk/act/test/ui/364/css-supports-transform-2/ - red background is hidden underneath rails using CSS transform for displaying. The test case starts with global movement across diagonal paths first, and after a while it starts following a straight path from top to bottom and from bottom to top. In that last sequence, webkit-based browsers tend to flicker i.e. to show red background for a split second for each movement.

The problem is very easy to spot using WPE WebKit 2.28 on low-end device like set-top box.
On the `Web` browser on ubuntu (`Web 3.36.4, A simple, clean, beautiful view of the web.
Powered by WebKitGTK 2.36.7`) I've seen the flickering continuously but only for split second each time.
Same goes for Safari 15.1 on Mac.

Thus I think there is some common WebKit problem we're facing here.

**Comment by magomez** [comment]
Wow, that page is an example of what not to do when designing a page for embedded.

I've tested this on the rpi3 and on the desktop, and I can't reproduce it on the desktop, basically because this is a simple performance problem and my laptop is quite powerful.

The main problem here is that the page is animating some huge elements (each row of images' width is 6000) pixels, and it's constantly moving content from out of the display to the display. Normally, the content that is outside of the display is not rendered (as it's not visible). But when an animation is pulling in some previously invisible content, it has to be rendered, and this happens during the animation. As there are a lot of elements and this rendering can take a while, the animation is not smooth (we lose some frames). This is noticeable in the first part of the test (the diagonal movement). 

The second part of the test is even worse, as there are more things happening:
- when the animation starts, all of the visible image rows content is copied into a new buffer in order to animate it. The background content needs to be repainted as well without the content that was copied into the new buffer. The redrawn content is a lot, which takes a while (on the rpi it's like 1 second).
- while this rendering is happening, the animation time is counting, so when the content is rendered and it's finally positioned on the display, the animation will have moved part of the content out of the display and pulled some content that was out of the display in. Due to this the content that was already rendered will be visible, but the part that has just become visible but wasn't rendered will be transparent, so the background content is visible. This is why when the element is animated moving down, the upper part of it will be transparent, and when it's animated moving up, the lower part of it becomes transparent. At this point the engine detects that it needs to render new content for that transparent area.
- after this initial incorrect display, the content that was pulled into the display will be rendered and displayed (on the rpi this takes like half a second). From this point on things go more or less fine.
- at the end the animated buffer content is destroyed and its content is painted back into the background content, but as there are no other things happening at this point, this is not a problem.
- when a new animation is started, the problem becomes visible again.

In general the engine is able to detect that the animation is pulling in some new content that needs to be rendered, and render it beforehand, but in this extreme case, the amount of time used rendering at the beginning of the animation is blocking the engine from doing so.

But I'm afraid this is yet another case of the cairo rendering being too slow and causing huge delays on hardware with slow CPUs. It's a know problem and it doesn't have a short term solution. And this test is an extreme case that's forcing a lot of cairo rendering, which makes things even worse.

**Comment by Scony** [comment]
Got it. Thanks @magomez for detailed explanation. I'll try to explain this to BBC then. I'll reopen this issue in case they insist we should somehow fix it.
