### ISSUE TITLE
[WPE2.22] Browser ignores URL change when js performs navigation to different #

### ISSUE THREAD

**Issue by jakub-gocol-red** [Metrological/WebKitForWayland#988]
Browser ignores URL change when js performs navigation to different #

Steps to reproduce:
1. Open Viaplay application
2. Around 1 second after loading spinner was shown, switch url to something else
```
curl -d '{"method": "WebKitBrowser.1.url", "params": "https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#boot"}' http://127.0.0.1:9998/jsonrpc
```

Expected behavior:
Browser should always switch url to requested one

Actual behavior:
Request failed. Browser is still on viaplay application.

Logs:
```
#sucesfully loaded viaplay
(operator())<2:6><1>: URL https://connected-devices.viaplay.com/?sourceType=2&journey=PERSONALHOME&appTileLocation=[object Object], load requested
(OnURLChanged)<2:6><1>: https://connected-devices.viaplay.com/?sourceType=2&journey=PERSONALHOME&appTileLocation=[object%20Object]
(OnLoadFinished)<2:6><1>: https://connected-devices.viaplay.com/?sourceType=2&journey=PERSONALHOME&appTileLocation=[object%20Object] (0xaf2c4d00|0xaf2c4d00)
(URL)<2:2><1>: URL: https://connected-devices.viaplay.com/?sourceType=2&journey=PERSONALHOME&appTileLocation=[object%20Object], load result OK(0), 861ms

#switched url to another one (just part after # changed)
(OnURLChanged)<2:6><1>: https://connected-devices.viaplay.com/?sourceType=2&journey=PERSONALHOME&appTileLocation=[object%20Object]#!country@pl

#leaving application (changing to entirely different domain)
(URL)<2:2><1>: New URL: https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#boot
(operator())<2:6><1>: URL https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#boot, load requested
(OnURLChanged)<2:6><1>: https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#boot

#load canceled...
(didFailNavigation)<2:6><1>: errorCode=302 (Load request cancelled), domain=WebKitNetworkError

#...because application decided to switch url to yet another one (also only part after # changed)
(OnURLChanged)<2:6><1>: https://connected-devices.viaplay.com/?sourceType=2&journey=PERSONALHOME&appTileLocation=[object%20Object]#!country@pl;retry@true
(URL)<2:2><1>: URL: https://connected-devices.viaplay.com/?sourceType=2&journey=PERSONALHOME&appTileLocation=[object%20Object]#!country@pl;retry@true, load result OK(0), 273ms
```

Reproduction with simple html:
1. Open this html in browser
```
<html>
<head>
<script>
let i = 0;
function changeLocation(){
    i+=1
    window.location.href = "#"+i;
    setTimeout(changeLocation,10)
}
changeLocation()
</script>
</head>
<body>
Navigation test
</body>
</html>
```
2. Switch url
``curl -d '{"method": "WebKitBrowser.1.url", "params": "https://google.com/"}' http://127.0.0.1:9998/jsonrpc``

URL switch will never succeed and browser will be stuck. 

In my opinion external url requests should never be cancelled by whatever javascript is doing. Especially if it just changes url fragment after #.

**Comment by jakub-gocol-red** [comment]
Mechanism that cancels request was introduced in [this](https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/d5123bad2239699df20948abc0f24acd5c655632#diff-d607936f085c93e3e1113e2c988f664830ab21dbe8351cfc08744a8b5112d473) commit. Reverting it fixed my issue.
But change seems intentional and was in use for more than 10 years now, although I still think that behavior is not correct. There should always be a way to reliably change URL.

**Comment by rychem** [comment]
@modeveci would you please share any update on this ticket?

**Comment by modeveci** [comment]
Hi @rychem, our team is quite busy with their current task list.  I believe in that, there will be update after holiday periods. Regards, Ozgur

**Comment by magomez** [comment]
I haven't been able to look into this yet, as I have many items on my TODO list. But I'm curious about why this is considered a bug, taking into account that this is an intended behavior (and it's still there on recent versions).

I'm reluctant to change this behavior for every case, but would be ok with adding an environment variable or a build option to control this behavior, so it can enabled and disabled on demand.

**Comment by jakub-gocol-red** [comment]
> But I'm curious about why this is considered a bug, taking into account that this is an intended behavior

Because we can't reliably change url, when viaplay application happened to navigate to different fragment.
As shown in example html, we might also not be able to change url at all. If it's user initiated action, it shouldn't just randomly fail.

**Comment by rychem** [comment]
@modeveci , @magomez, hopefully Jakub's explanations makes clear background of this ticket.
Please kindly share your plans regarding this ticket.

**Comment by magomez** [comment]
I've just pushed 525d2d60d8387773a023f7ae67c74c3b06430457 to the wpe-2.22 branch.
With this change, the env var WPE_KEEP_NAVIGATION_ON_FRAGMENT_LOAD can be used to modify the default behavior, so fragment loading doesn't cancel existing navigation requests. Please use that env var in your environment, and close this issue if your problem is fixed.

**Comment by jakub-gocol-red** [comment]
@magomez Thanks for the patch.
But keeping it behind disabled by default flag suggests that we're not really sure what the correct behaviour is. When I created this ticket my goal was to get some help from people, that have much better understanding of webkit internals than I do. I wanted to understand what browser correct behaviour should be, or what user of api should do differently. With this env var, we have at best one correct and one broken behaviour. But we might as well have both of them wrong.

**Comment by magomez** [comment]
I've been searching for documentation about this but I haven't been able to find much, specially related to WebKit. I found some info about chromium detecting situations about navigations initiated by the page causing possible DoS attacks (like the case with the js test you provided). In order to protect from these cases, they distinguish whether the navigation comes from some user interaction or not. If the user was involved, then the navigation will cancel an existing navigation initiated by the API/browser. If the used was not involved, then the navigation is not allowed to cancel other API/browser navigations.

I don't know what's the status of this in WebKIt, or whether something like that is implemented. I can only guess that the current status is intended and was added to fix some issue when it was done. Also, I don't know whether other measures may be implemented in other places of the code, or whether something like the chrome approach is in place. I'm not an expert on those parts of the code. I'm sorry I can't be more helpful.

Then regarding the fix: I'm keeping the change disabled not because I'm not sure whether it's the correct behavior or not. I'm doing it because there are millions of devices running 2.22 and this is the first time a problem like this is reported, and I prefer to avoid the risk of creating a regression on those platforms and allow the change to be enabled on demand for those that need it.

**Comment by jacek-skiba-red** [comment]
Commit which introduced this behavior (https://bugs.webkit.org/show_bug.cgi?id=64556) was a fix for CVE-2011-2845 issue:
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2011-2845

Here is a detail description of this vulnerability: https://bugs.chromium.org/p/chromium/issues/detail?id=86758

In general, this vulnerability is related to 2 tabs scenario and having URL presented in URL bar. 
This vulnerability is not risky in STB enironment, but reverting it in upstream is also not recommented. 
Implementation under env seems reasonable.
